providers = ["python"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Skip frontend build for Railway'"
]

[start]
cmd = "uvicorn backend.backend_stress_test:app --host 0.0.0.0 --port 8000"
