providers = ["python"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade || true",
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Skip frontend build for Railway'"
]

[start]
cmd = "uvicorn backend.backend_stress_test:app --host 0.0.0.0 --port 8000"
