providers = ["node"]
<<<<<<< Current (Your changes)

[phases.install]
<<<<<<< Current (Your changes)
commands = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py",
  "python3 /tmp/get-pip.py",
  "python3 -m pip install --upgrade pip setuptools wheel",
  "python3 -m pip install -r backend/requirements.txt"
]

[phases.build]
commands = [
  "echo 'Skip frontend build for Railway'"
]

[start]
cmd = "python3 -m uvicorn backend.backend_stress_test:app --host 0.0.0.0 --port $PORT"
=======
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"
<<<<<<< Current (Your changes)
>>>>>>> Incoming (Background Agent changes)
=======
>>>>>>> Incoming (Background Agent changes)
=======

[start]
cmd = "npm start"
>>>>>>> Incoming (Background Agent changes)
