[build]
builder = "NIXPACKS"
installCommand = "pip install -r backend/requirements.txt"
buildCommand = "echo 'Skip frontend build for Railway'"

[deploy]
startCommand = "uvicorn backend.backend_stress_test:app --host 0.0.0.0 --port 8000"
