 <<<<<<< Current (Your changes)
[build]
builder = "NIXPACKS"
<<<<<<< Current (Your changes)
<<<<<<< Current (Your changes)
installCommand = "python3 -m pip install -r backend/requirements.txt"
buildCommand = "echo 'Skip frontend build for Railway'"

[deploy]
startCommand = "python -m uvicorn backend.backend_stress_test:app --host 0.0.0.0 --port $PORT"
=======

[deploy]
startCommand = "npm start"
>>>>>>> Incoming (Background Agent changes)
=======

[deploy]
startCommand = "npm start"
>>>>>>> Incoming (Background Agent changes)
=======
[deploy]
startCommand = "npm start"
>>>>>>> Incoming (Background Agent changes)
